language: python

os:
  - linux

sudo: false

cache: pip

script:
  - tox

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=pep8
    - python: 3.6
      script: pyq _test
      install: pip install .
